apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: psp-util
spec:
  description: |
    A Kubectl plugin to manage Pod Security Policy(PSP) and the related RBAC Resources.
    Attach/Detach PSP to/from RBACs(Group, User) or ServiceAccounts and
    view the relations which PSP is effected to the Subjects in cluster.
  homepage: https://github.com/jlandowner/psp-util
  platforms:
  - bin: psp-util
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    {{addURIAndSha "https://github.com/jlandowner/psp-util/releases/download/{{ .TagName }}/psp-util_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
  - bin: psp-util
    selector:
      matchLabels:
        arch: amd64
        os: linux
    {{addURIAndSha "https://github.com/jlandowner/psp-util/releases/download/{{ .TagName }}/psp-util_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
  - bin: psp-util
    selector:
      matchLabels:
        arch: amd64
        os: windows
    {{addURIAndSha "https://github.com/jlandowner/psp-util/releases/download/{{ .TagName }}/psp-util_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
  shortDescription: Manage Pod Security Policy(PSP) and the related RBACs
  version: {{ .TagName }}
