apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: psp-util
spec:
  description: |
    A Kubectl plugin to manage Pod Security Policy(PSP) and the related RBAC Resources.
    Attach/Detach PSP to/from RBACs(Group, User) or ServiceAccounts and
    view the relations which PSP is effected to the Subjects in cluster.
  homepage: https://github.com/jlandowner/psp-util
  platforms:
  - bin: psp-util
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 43fc6e8e8c6dd780b86f9a3a39dcbfbfe6dde48bbbd9500df18616ff88021956
    uri: https://github.com/jlandowner/psp-util/releases/download/v1.0.0/psp-util_v1.0.0_darwin_amd64.tar.gz
  - bin: psp-util
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: ce66ecb8b2975dfb4d15b9faa95d7e3eefefb3088a15f8eb9310f0b443ad3f50
    uri: https://github.com/jlandowner/psp-util/releases/download/v1.0.0/psp-util_v1.0.0_linux_amd64.tar.gz
  shortDescription: Manage Pod Security Policy(PSP) and the related RBACs
  version: v1.0.0
